\input texinfo   @c -*-texinfo-*-
@comment %**start of header
@setfilename dydra.info
@finalout
@set UPDATED 13 May 2011
@set UPDATED-MONTH May 2011
@set EDITION 2011.05.13
@set VERSION 2011.05.13
@settitle Dydra Developer Guide @value{UPDATED}
@documentencoding UTF-8
@comment %**end of header

@copying
This document is in the public domain.
Anyone is free to copy, modify, publish, use, compile, sell, or distribute
this document for any purpose, commercial or non-commercial, and by any
means.
@end copying

@titlepage
@title Dydra Developer Guide
@subtitle @value{UPDATED}
@author @url{http://dydra.com}
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Dydra Developer Guide
@end ifnottex

@menu
* About this Document::
* Introduction to Dydra::
* Understanding Dydra::
* Developing with Dydra::
* API Reference::
* API Error Conditions::
* Concept Index::
* Function Index::
@end menu

@node About this Document
@chapter About this Document

This is the developer guide for Dydra. It provides a conceptual overview of
Dydra, programming reference material, and a detailed API reference.

@node Introduction to Dydra
@chapter Introduction to Dydra

@node Understanding Dydra
@chapter Understanding Dydra

@node Developing with Dydra
@chapter Developing with Dydra

@node API Reference
@chapter API Reference
@cindex API, reference

This chapter contains detailed descriptions of all Dydra API operations,
their request parameters, and their responses and error conditions. It also
contains concrete on-the-wire examples of requests and responses for each
operation.

@include api/rpc/types.texi

@node API Error Conditions
@chapter API Error Conditions
@cindex API, error codes

This chapter describes the various error conditions raised by Dydra API
operations.

@include api/rpc/errors.texi

@comment Glossary
@include guide/glossary.texi

@node Concept Index
@unnumbered Concept Index
@printindex cp

@node Operation Index
@unnumbered Operation Index
@printindex fn

@bye
